bundles:
    common:
        config: \Uecode\Bundle\CommonBundle\DependencyInjection\Configuration
    amazon:
        config: \Uecode\Bundle\AmazonBundle\DependencyInjection\Configuration
    daemon:
        config: \Uecode\Bundle\DaemonBundle\DependencyInjection\Configuration
